{% set name = "uldaq" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e3def9bee06e37129b18654c9ac2c6804511c8d80ffb559d4aa886ecf6bcef5
  patches:
    - 0001-ul_c_interface-use-ctypes.util.find_library.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - libuldaq
    - python

test:
  imports:
    - uldaq

about:
  home: http://www.mccdaq.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Universal Library Python API for Measurement Computing DAQ devices
  doc_url: https://www.mccdaq.com/PDFs/Manuals/UL-Linux/python

extra:
  recipe-maintainers:
    - jdowner
